language: objective-c
os: osx
osx_image: xcode10
before_install:
  - gem install xcpretty
before_script:
  - set -o pipefail
script:
  - xcodebuild test -project ./AttributedLabel.xcodeproj -scheme AttributedLabelTests -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty -c
notifications:
  email: false
